### PR TITLE
Register curl clone post

### PR DESCRIPTION
**Pull request by jjatria**
While developing HTTP::Tiny I wrote a curl clone that allowed me to make sure it worked and to compare its results with the real curl.

This post would work as a showcase of the kind of things that the library supports and the HTTP::Tiny interface allows.

### CODE REVIEW

**Comment by JJ** [comment]
Thanks!

**Comment by JJ** [comment]
Please have the article ready one week from now. I'd like to have all articles soon-ish to not have to request last-minute posts like it's usual.

**Comment by JJ** [comment]
How's this coming along?

**Comment by jjatria** [comment]
@jj I'm trying to get a complete version of this as soon as possible. Being in the intersection of academia and software development, you are undoubtedly familiar with overstating one's abilities and missing your deadlines. :)

I should have something to show you today or Sunday at the latest :sweat_drops:

**Comment by jjatria** [comment]
@jj: I've finished a first draft: https://gist.github.com/jjatria/62b570f9fba2acb80bb5d6b8afaf5d6f

I realised the curl clone post was not easy to write in a way that was suitable for beginners, and the more i thought about it, the more I wanted to write about Timer::Stopwatch instead. I hope the change of subject is OK, and I feel like this is much more inviting.

**Pull request merged**
