### PR TITLE
Update schedule

### PR DESCRIPTION
**Pull request by MorayJ**
Change name of article

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Buildnig? :)

**Comment by JJ** [comment]
I have edited the comments in the first example so that they don't disappear in the box, putting them over the token and also adding | to make them appear in the documentation. It would be nice to do that with the rest of the examples, although it takes some time because, for some reason, it can't be done from the visual... I can do it along the day if nobody does it first. Great job, anyway, @Altai-man and @MorayJ

**Comment by MorayJ** [comment]
I'm a little afraid to touch it - when I was editing, when I changed something it would turn all the &lt; back to chevrons and make a mess. There are a couple of words where this has happened so the word has disappeared, but they're mainly in the comments. I'll maybe edit tomorrow when it's not on the front page...

**Comment by MorayJ** [comment]
@Altai-man @JJ Thanks for the lead in formatting this post and the work you did on it. I have been through following both of your advice and hopefully it's pretty clear now...

**Comment by JJ** [comment]
It looks much better now, thanks. I have just added again the "More" line so that it only shows a stub in the front page.

**Comment by MorayJ** [comment]
I'm not having much luck with Wordpress! After your amendment, a couple of `&lt;`s corrupted again. I fixed them and put the 'more' back, but it's not actually doing the 'More' anymore

EDIT: It's ok, it's working...

**Comment by JJ** [comment]
No worries...

**Pull request merged**
