### PR TITLE
Add Kaiepi as an author

### PR DESCRIPTION
**Pull request by Kaiepi**
Just about all the Raku I write nowadays is typed. How to leverage Raku's type system is something I struggled with initially, so I figure an advent article on some strategies I use when typing my code would be helpful for others interested in doing this.

### CODE REVIEW

**Comment by JJ** [comment]
If possible, I'd like to have the articles one week from now, in the usual way: either at the blog directly or here as a markdown file.

**Comment by JJ** [comment]
How's the article going?

**Comment by Kaiepi** [comment]
The first part's just about finished. I know what I'll be talking about in the second one, just need to come up with some examples for it.

**Comment by Kaiepi** [comment]
I have examples in mind. I'll try to get it finished before Monday.

**Comment by JJ** [comment]
Thanks bunches!

**Pull request merged**
