### PR TITLE
Fix typos/spellos/grammaros/spaceos

### PR DESCRIPTION
**Pull request by raiph**

### CODE REVIEW

**Review by JJ — APPROVED** [review]
Of course, it needs to be @codesections who merges it.

**Review by raiph — COMMENTED** [review]
Gah. I now see typos in my typo fixes. You presumably meant:

> **that** one domino that the entire Internet **depend** on

to be :

> **the** one domino that the entire Internet **depended** on

And:

> [studies](https://steve-yegge.blogspot.com/2007/12/codes-worst-enemy.html) [have shown](https://www.mayerdan.com/ruby/2012/11/11/bugs-per-line-of-code-ratio) [over](https://blog.codinghorror.com/diseconomies-of-scale-and-lines-of-code/) over and [over again](https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670)

to be more like:

> [studies](https://steve-yegge.blogspot.com/2007/12/codes-worst-enemy.html) have shown [over](https://www.mayerdan.com/ruby/2012/11/11/bugs-per-line-of-code-ratio) and [over](https://blog.codinghorror.com/diseconomies-of-scale-and-lines-of-code/) and [over again](https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670)

Here's the markdown for that last quote so you can cut/paste it:
```
[studies](https://steve-yegge.blogspot.com/2007/12/codes-worst-enemy.html) have shown [over](https://www.mayerdan.com/ruby/2012/11/11/bugs-per-line-of-code-ratio) and [over](https://blog.codinghorror.com/diseconomies-of-scale-and-lines-of-code/) and [over again](https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670)
```

**Comment by codesections** [comment]
Thanks for all these!  Some of the spacing issues were removed in the md →html conversion and I've fixed the other issues you pointed out.

I look forward to your hearing any substantive thoughts you might have once the post goes live.

**Comment by JJ** [comment]
Should we merge this?

**Comment by JJ** [comment]
I guess I'll close it. Thanks!

**Pull request closed without merging**
